font_family      FiraCode Nerd Font
font_size        13.0

background_opacity 0.75
dynamic_background_opacity yes
background_blur 32

foreground              #dce7cf
background              #0c140e
selection_foreground    #ffffff
selection_background    #1d3e26

cursor                  #dec07e
cursor_text_color       #0c140e

# Black
color0   #0c140e
color8   #243d2b

# Red
color1   #d4574a
color9   #ff7a6b

# Green (Emerald)
color2   #78c45d
color10  #96e077

# Yellow / Gold (Brass)
color3   #dec07e
color11  #fed594

# Blue
color4   #5aa8c0
color12  #7ec7ea

# Magenta
color5   #b07ea6
color13  #d8a0cd

# Cyan
color6   #6bc5b8
color14  #8fe5d8

# White
color7   #dce7cf
color15  #ffffff

active_tab_foreground   #0c140e
active_tab_background   #dec07e
inactive_tab_foreground #a3c299
inactive_tab_background #14281a

active_border_color     #dec07e
inactive_border_color   #172b1c
