# Wayland & Desktop Standard Environment Variables
XDG_CURRENT_DESKTOP=niri
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=niri

# Toolkit Backends
QT_QPA_PLATFORM=wayland;xcb
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
CLUTTER_BACKEND=wayland
SDL_VIDEODRIVER=wayland,x11

# Browsers & Electron
MOZ_ENABLE_WAYLAND=1
ELECTRON_OZONE_PLATFORM_HINT=auto
CHROME_EXECUTABLE=/usr/bin/firefox

# Java GUI WM Fix
_JAVA_AWT_WM_NONREPARENTING=1

# NVIDIA Wayland & Hardware Acceleration
LIBVA_DRIVER_NAME=nvidia
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
NVD_BACKEND=direct
