--ozone-platform=wayland
--enable-features=WebRTCPipeWireCapturer,WaylandWindowDecorations
--disable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
--disable-gpu-sandbox
--remote-debugging-port=9222
